Repository smileidentity/android, pull requests merged in 2025-02, with the labels that each got.

#539 Prepare 10.4.3
  lib/VERSION
Labels: Review effort [1-5]: 1

#537 use ISO8601 format for timestamp on all SDKs.
  CHANGELOG.md
  lib/src/main/java/com/smileidentity/models/Bvn.kt
  lib/src/main/java/com/smileidentity/models/EnhancedKyc.kt
  lib/src/main/java/com/smileidentity/models/JobStatus.kt
  lib/src/main/java/com/smileidentity/models/PrepUpload.kt
  lib/src/main/java/com/smileidentity/models/ProductsConfig.kt
  lib/src/main/java/com/smileidentity/util/Util.kt
Labels: Review effort [1-5]: 2

#538 Add Biometric Consent Information 🔨
  CHANGELOG.md
  lib/src/main/java/com/smileidentity/compose/SmileIDExt.kt
  lib/src/main/java/com/smileidentity/compose/biometric/OrchestratedBiometricKYCScreen.kt
  lib/src/main/java/com/smileidentity/compose/consent/ConsentScreen.kt
  lib/src/main/java/com/smileidentity/compose/consent/OrchestratedConsentScreen.kt
  lib/src/main/java/com/smileidentity/compose/consent/bvn/OrchestratedBvnConsentScreen.kt
  lib/src/main/java/com/smileidentity/fragment/BiometricKYCFragment.kt
  lib/src/main/java/com/smileidentity/models/EnhancedKyc.kt
  lib/src/main/java/com/smileidentity/models/Upload.kt
  lib/src/main/java/com/smileidentity/viewmodel/BiometricKycViewModel.kt
  lib/src/test/java/com/smileidentity/networking/EnhancedKycTest.kt
  sample/src/main/java/com/smileidentity/sample/Utils.kt
  sample/src/main/java/com/smileidentity/sample/activity/JavaActivity.java
  sample/src/main/java/com/smileidentity/sample/compose/MainScreen.kt
  sample/src/main/java/com/smileidentity/sample/compose/OrchestratedEnhancedKycScreen.kt
  sample/src/main/java/com/smileidentity/sample/compose/components/IdTypeSelectorAndFieldInputScreen.kt
  sample/src/main/java/com/smileidentity/sample/viewmodel/EnhancedKycViewModel.kt
  sample/src/main/java/com/smileidentity/sample/viewmodel/IdTypeSelectorAndFieldInputViewModel.kt
Labels: Review effort [1-5]: 3

#543 Add Consent Information to EnhancedDocV 📸
  CHANGELOG.md
  lib/src/main/java/com/smileidentity/compose/SmileIDExt.kt
  lib/src/main/java/com/smileidentity/fragment/EnhancedDocumentVerificationFragment.kt
  lib/src/main/java/com/smileidentity/models/Upload.kt
  lib/src/main/java/com/smileidentity/viewmodel/document/OrchestratedDocumentViewModel.kt
  lib/src/test/java/com/smileidentity/viewmodel/document/EnhancedDocumentVerificationViewModelTest.kt
  sample/src/main/java/com/smileidentity/sample/activity/JavaActivity.java
  sample/src/main/java/com/smileidentity/sample/compose/MainScreen.kt
  sample/src/main/java/com/smileidentity/sample/compose/components/IdTypeSelectorScreen.kt
Labels: Review effort [1-5]: 2, Possible security concern

#544 Disable Network Retries 🌍
  CHANGELOG.md
  lib/src/main/java/com/smileidentity/SmileID.kt
Labels: Review effort [1-5]: 3

#553 Debug Actions
  .github/workflows/build.yaml
  .github/workflows/release_sdk.yaml
  lib/lib.gradle.kts
Labels: Review effort [1-5]: 2
