Repository smileidentity/android, pull requests merged in 2025-09, with the labels that each got.

#740 feat: enhance integrity token provider warmup and error reporting
  attestation/src/main/java/com/smileidentity/attestation/SmileIDIntegrityManager.kt
  attestation/src/test/java/com/smileidentity/attestation/SmileIDIntegrityManagerTest.kt
  lib/src/main/java/com/smileidentity/SmileID.kt
  lib/src/main/java/com/smileidentity/SmileIDCrashReporting.kt
  lib/src/main/java/com/smileidentity/networking/SmileIDIntegrityInterceptor.kt
Labels: Review effort 3/5

#745 Payload Signing Policy Check 🚓
  gradle/libs.versions.toml
  lib/src/main/java/com/smileidentity/SmileID.kt
  lib/src/main/java/com/smileidentity/networking/NetworkingUtil.kt
  lib/src/main/java/com/smileidentity/networking/SmileHeaderAuthInterceptor.kt
  lib/src/main/java/com/smileidentity/viewmodel/BiometricKycViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/document/OrchestratedDocumentViewModel.kt
Labels: Review effort 3/5

#746 Prepare v11.1.1 Release ☺️
  CHANGELOG.md
  gradle/libs.versions.toml
  lib/VERSION
Labels: Review effort 1/5

#753 Remove RootBeer 🍺
  gradle/libs.versions.toml
  lib/lib.gradle.kts
  lib/src/main/java/com/smileidentity/SmileID.kt
Labels: Review effort 3/5

#755 Move Attestation Logic to Lib Module
  .github/workflows/attestation_release_sdk.yaml
  .github/workflows/build.yaml
  CHANGELOG.md
  attestation/attestation.gradle.kts
  lib/lib.gradle.kts
  lib/src/main/java/com/smileidentity/attestation/SmileIDIntegrityManager.kt
  lib/src/main/java/com/smileidentity/attestation/SmileIDIntegrityManagerFactory.kt
  lib/src/main/java/com/smileidentity/attestation/TaskExtensions.kt
  lib/src/test/java/com/smileidentity/attestation/SmileIDIntegrityManagerTest.kt
Labels: Review effort 3/5

#757 Add attestation certificate chain to metadata
  lib/src/main/java/com/smileidentity/metadata/models/MetadataKey.kt
  lib/src/main/java/com/smileidentity/metadata/models/Metadatum.kt
  lib/src/main/java/com/smileidentity/metadata/updaters/AttestationMetadata.kt
Labels: Review effort 4/5

#754 Supports Hardware attestation metadata
  lib/src/main/java/com/smileidentity/metadata/LocalMetadataProvider.kt
  lib/src/main/java/com/smileidentity/metadata/models/MetadataKey.kt
  lib/src/main/java/com/smileidentity/metadata/models/Metadatum.kt
  lib/src/main/java/com/smileidentity/metadata/updaters/AttestationMetadata.kt
Labels: Review effort 3/5

#758 Prepare v11.1.2 💮
  CHANGELOG.md
  gradle/libs.versions.toml
  lib/VERSION
  lib/src/main/AndroidManifest.xml
Labels: Review effort 1/5

#759 fix: Automatic release generation on the docs
  .github/workflows/post_release.yml
Labels: Review effort 1/5

#765 Hello Koin 🪙💰
  analytics/analytics.gradle.kts
  attestation/attestation.gradle.kts
  build-logic/convention/build.gradle.kts
  build-logic/convention/src/main/kotlin/KoinConventionPlugin.kt
  camera/camera.gradle.kts
  gradle/libs.versions.toml
  ml/ml.gradle.kts
  navigation/navigation.gradle.kts
  networking/networking.gradle.kts
  storage/storage.gradle.kts
  ui/ui.gradle.kts
Labels: Review effort 2/5
