Repository smileidentity/android, pull requests merged in 2025-01, with the labels that each got.

#514 Fix throw IOException
  CHANGELOG.md
  lib/src/main/java/com/smileidentity/networking/Retrofit.kt
Labels: Review effort [1-5]: 2

#518 Updated Github Lint Action
  .github/workflows/build.yaml
Labels: Review effort [1-5]: 1

#520 chore: bump version
  lib/VERSION
Labels: Review effort [1-5]: 1

#526 Enable manual workflow trigger
  .github/workflows/publish_play_store_update.yaml
Labels: Review effort [1-5]: 1

#524 Revert Navigation Changes
  lib/src/main/java/com/smileidentity/compose/SmileIDExt.kt
  lib/src/main/java/com/smileidentity/compose/biometric/OrchestratedBiometricKYCScreen.kt
  lib/src/main/java/com/smileidentity/compose/document/CaptureScreenContent.kt
  lib/src/main/java/com/smileidentity/compose/document/DocumentCaptureInstructionsScreen.kt
  lib/src/main/java/com/smileidentity/compose/document/DocumentCaptureScreen.kt
  lib/src/main/java/com/smileidentity/compose/document/OrchestratedDocumentVerificationScreen.kt
  lib/src/main/java/com/smileidentity/compose/nav/MultiNavigationState.kt
  lib/src/main/java/com/smileidentity/compose/nav/NavRoutesParams.kt
  lib/src/main/java/com/smileidentity/compose/nav/NavUtil.kt
  lib/src/main/java/com/smileidentity/compose/nav/NavigationBackHandler.kt
  lib/src/main/java/com/smileidentity/compose/nav/PersistentMapSerializer.kt
  lib/src/main/java/com/smileidentity/compose/nav/Routes.kt
  lib/src/main/java/com/smileidentity/compose/nav/SmileIDNav.kt
  lib/src/main/java/com/smileidentity/compose/selfie/OrchestratedSelfieCaptureScreen.kt
  lib/src/main/java/com/smileidentity/fragment/DocumentVerificationFragment.kt
  lib/src/main/java/com/smileidentity/fragment/EnhancedDocumentVerificationFragment.kt
  lib/src/main/java/com/smileidentity/fragment/SmartSelfieAuthenticationFragment.kt
  lib/src/main/java/com/smileidentity/fragment/SmartSelfieEnrollmentFragment.kt
  lib/src/main/java/com/smileidentity/viewmodel/document/OrchestratedDocumentViewModel.kt
  lib/src/test/java/com/smileidentity/viewmodel/document/DocumentViewModelTest.kt
  lib/src/test/java/com/smileidentity/viewmodel/document/EnhancedDocumentVerificationViewModelTest.kt
Labels: Review effort [1-5]: 4

#530 feat: update changelog
  CHANGELOG.md
Labels: Review effort [1-5]: 1
