Repository smileidentity/android, pull requests merged in 2025-05, with the labels that each got.

#603 Feature/wrapper event structure and proper datatypes
  lib/src/main/java/com/smileidentity/SmileID.kt
  lib/src/main/java/com/smileidentity/models/EnhancedKyc.kt
  lib/src/main/java/com/smileidentity/models/PrepUpload.kt
  lib/src/main/java/com/smileidentity/models/v2/metadata/ApplicationInfoProvider.kt
  lib/src/main/java/com/smileidentity/models/v2/metadata/CarrierInfoProvider.kt
  lib/src/main/java/com/smileidentity/models/v2/metadata/DeviceInfoProvider.kt
  lib/src/main/java/com/smileidentity/models/v2/metadata/MetadataEntry.kt
  lib/src/main/java/com/smileidentity/models/v2/metadata/MetadataManager.kt
  lib/src/main/java/com/smileidentity/models/v2/metadata/Metadatum.kt
  lib/src/main/java/com/smileidentity/models/v2/metadata/NetworkMetadataProvider.kt
  lib/src/main/java/com/smileidentity/viewmodel/BiometricKycViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/SelfieViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/SmartSelfieEnhancedViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/document/OrchestratedDocumentViewModel.kt
Labels: Review effort 4/5

#611 Auto assign
  .github/dependabot.yaml
Labels: Review effort 1/5

#614 feat: correct consent field names
  CHANGELOG.md
  lib/src/main/java/com/smileidentity/compose/SmileIDExt.kt
  lib/src/main/java/com/smileidentity/compose/consent/ConsentScreen.kt
  lib/src/main/java/com/smileidentity/compose/consent/bvn/OrchestratedBvnConsentScreen.kt
  lib/src/main/java/com/smileidentity/fragment/BiometricKYCFragment.kt
  lib/src/main/java/com/smileidentity/fragment/EnhancedDocumentVerificationFragment.kt
  lib/src/main/java/com/smileidentity/models/EnhancedKyc.kt
  lib/src/main/java/com/smileidentity/models/Upload.kt
  lib/src/test/java/com/smileidentity/models/ConsentInformationTest.kt
  lib/src/test/java/com/smileidentity/networking/EnhancedKycTest.kt
  lib/src/test/java/com/smileidentity/viewmodel/document/EnhancedDocumentVerificationViewModelTest.kt
  sample/src/main/java/com/smileidentity/sample/activity/JavaActivity.java
  sample/src/main/java/com/smileidentity/sample/viewmodel/IdTypeSelectorAndFieldInputViewModel.kt
Labels: Review effort 2/5

#617 Update ktlint version
  .github/workflows/build.yaml
  lib/src/main/java/com/smileidentity/SmileID.kt
  lib/src/main/java/com/smileidentity/SmileIDCrashReporting.kt
  lib/src/main/java/com/smileidentity/compose/components/OvalCutout.kt
  lib/src/main/java/com/smileidentity/models/DocumentCaptureFlow.kt
  lib/src/main/java/com/smileidentity/models/JobStatus.kt
  lib/src/main/java/com/smileidentity/models/Models.kt
  lib/src/main/java/com/smileidentity/models/Services.kt
  lib/src/main/java/com/smileidentity/models/Upload.kt
  lib/src/main/java/com/smileidentity/models/v2/Metadata.kt
  lib/src/main/java/com/smileidentity/networking/GzipRequestInterceptor.kt
  lib/src/main/java/com/smileidentity/results/SmileIDResult.kt
  lib/src/main/java/com/smileidentity/util/FileUtils.kt
  lib/src/main/java/com/smileidentity/util/SpanFormatter.kt
  lib/src/main/java/com/smileidentity/util/Util.kt
  lib/src/main/java/com/smileidentity/viewmodel/BiometricKycViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/BvnConsentViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/SmartSelfieEnhancedViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/document/DocumentCaptureViewModel.kt
  sample/src/main/java/com/smileidentity/sample/Utils.kt
  sample/src/main/java/com/smileidentity/sample/compose/RootScreen.kt
  sample/src/main/java/com/smileidentity/sample/model/Job.kt
  sample/src/main/java/com/smileidentity/sample/repo/DataStoreRepository.kt
  sample/src/main/java/com/smileidentity/sample/viewmodel/IdTypeSelectorAndFieldInputViewModel.kt
Labels: Review effort 1/5

#619 Fix Show Attribution for Enhanced Selfie Flow
  CHANGELOG.md
  lib/VERSION
  lib/src/main/java/com/smileidentity/compose/selfie/enhanced/SelfieCaptureScreenEnhanced.kt
Labels: Review effort 1/5

#612 Rework File Storage and Error Handling
  CHANGELOG.md
  lib/src/main/java/com/smileidentity/SmileID.kt
  lib/src/main/java/com/smileidentity/compose/document/DocumentCaptureScreen.kt
  lib/src/main/java/com/smileidentity/compose/selfie/OrchestratedSelfieCaptureScreen.kt
  lib/src/main/java/com/smileidentity/util/FileUtils.kt
  lib/src/main/java/com/smileidentity/viewmodel/SelfieViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/document/DocumentCaptureViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/document/OrchestratedDocumentViewModel.kt
  lib/src/test/java/com/smileidentity/SmileIDTest.kt
  lib/src/test/java/com/smileidentity/util/FileUtilsTest.kt
Labels: Review effort 3/5

#624 Feat/add geolocation and accelerometer
  gradle/libs.versions.toml
  lib/lib.gradle.kts
  lib/src/main/java/com/smileidentity/metadata/LocalMetadataProvider.kt
  lib/src/main/java/com/smileidentity/metadata/Metadata.kt
  lib/src/main/java/com/smileidentity/metadata/models/MetadataKey.kt
  lib/src/main/java/com/smileidentity/metadata/models/Metadatum.kt
  lib/src/main/java/com/smileidentity/metadata/updaters/DeviceOrientationMetadata.kt
  lib/src/main/java/com/smileidentity/metadata/updaters/LocationMetadata.kt
  lib/src/main/java/com/smileidentity/networking/Retrofit.kt
  lib/src/main/java/com/smileidentity/networking/ValueParceler.kt
  lib/src/main/java/com/smileidentity/viewmodel/BiometricKycViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/SelfieViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/SmartSelfieEnhancedViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/document/DocumentCaptureViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/document/OrchestratedDocumentViewModel.kt
  sample/src/main/AndroidManifest.xml
  sample/src/main/java/com/smileidentity/sample/activity/MainActivity.kt
Labels: Review effort 3/5

#536 Update Request Header
  .github/workflows/release_sdk.yaml
  CHANGELOG.md
  gradle/libs.versions.toml
  lib/VERSION
  lib/lib.gradle.kts
  lib/src/main/java/com/smileidentity/SmileID.kt
  lib/src/main/java/com/smileidentity/models/Upload.kt
  lib/src/main/java/com/smileidentity/networking/NetworkingUtil.kt
  lib/src/main/java/com/smileidentity/networking/SmileHeaderMetadataInterceptor.kt
  lib/src/main/java/com/smileidentity/networking/SmileIDService.kt
  lib/src/test/java/com/smileidentity/networking/UploadRequestConverterTest.kt
  lib/src/test/java/com/smileidentity/viewmodel/document/DocumentViewModelTest.kt
  lib/src/test/java/com/smileidentity/viewmodel/document/EnhancedDocumentVerificationViewModelTest.kt
  sample/sample.gradle.kts
  settings.gradle.kts
Labels: Review effort 3/5

#628 Fix Version Suffix ㊙️
  lib/VERSION
Labels: Review effort 1/5
