Repository smileidentity/android, pull requests merged in 2025-07, with the labels that each got.

#659 Fix Welcome Screen Continue Button
  sample/src/main/java/com/smileidentity/sample/compose/RootScreen.kt
  sample/src/main/java/com/smileidentity/sample/viewmodel/RootViewModel.kt
Labels: Review effort 2/5

#662 Enable or Disable Auto Capture on DocV and Enhanced DocV 📸
  CHANGELOG.md
  lib/src/main/java/com/smileidentity/compose/SmileIDExt.kt
  lib/src/main/java/com/smileidentity/compose/document/DocumentCaptureScreen.kt
  lib/src/main/java/com/smileidentity/compose/document/OrchestratedDocumentVerificationScreen.kt
  lib/src/main/java/com/smileidentity/viewmodel/document/DocumentCaptureViewModel.kt
  lib/src/test/java/com/smileidentity/viewmodel/document/DocumentCaptureViewModelTest.kt
Labels: Review effort 3/5

#663 chore: update liteRT dependencies to version 1.4.0
  gradle/libs.versions.toml
Labels: Review effort 1/5

#652 Improve Smart Selfie Capture ⚒️
  lib/src/main/java/com/smileidentity/compose/components/OvalCutout.kt
  lib/src/main/java/com/smileidentity/util/FaceUtil.kt
  lib/src/main/java/com/smileidentity/util/Util.kt
Labels: Review effort 4/5

#658 Improve Selfie Capture
  CHANGELOG.md
  lib/src/main/java/com/smileidentity/compose/selfie/SelfieCaptureScreen.kt
  lib/src/main/java/com/smileidentity/viewmodel/SelfieViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/SmartSelfieEnhancedViewModel.kt
Labels: Review effort 3/5

#676 Update CHANGELOG
  CHANGELOG.md
Labels: Review effort 1/5

#677 Remove Default Consent Information 🦁
  CHANGELOG.md
  lib/VERSION
  lib/src/main/java/com/smileidentity/compose/SmileIDExt.kt
  lib/src/main/java/com/smileidentity/compose/biometric/OrchestratedBiometricKYCScreen.kt
  lib/src/main/java/com/smileidentity/viewmodel/BiometricKycViewModel.kt
  lib/src/main/java/com/smileidentity/viewmodel/document/OrchestratedDocumentViewModel.kt
Labels: Review effort 3/5

#678 UI Modularization 👨🏽‍🎨
  settings.gradle.kts
  ui/.gitignore
  ui/consumer-rules.pro
  ui/proguard-rules.pro
  ui/src/androidTest/java/com/smileidentity/ui/ExampleInstrumentedTest.kt
  ui/src/main/AndroidManifest.xml
  ui/ui.gradle.kts
Labels: Review effort 3/5

#685 Setup ML Face Analyzers 🧣
  build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt
  camera/src/main/java/com/smileidentity/camera/Analyzer.kt
  ml/ml.gradle.kts
  ml/src/androidTest/java/com/smileidentity/ml/ExampleInstrumentedTest.kt
  ml/src/main/java/com/smileidentity/ml/detectors/DocumentDetectorAnalyzer.kt
  ml/src/main/java/com/smileidentity/ml/detectors/FaceDetectorAnalyzer.kt
  ml/src/main/java/com/smileidentity/ml/detectors/Model.kt
  ml/src/main/java/com/smileidentity/ml/states/IdentityScanState.kt
  ml/src/main/java/com/smileidentity/ml/states/IdentityScanStateTransitioner.kt
  ml/src/test/java/com/smileidentity/ml/ExampleUnitTest.kt
Labels: Review effort 3/5

#690 Use Arkana to manage SentryDSN 🙈
  .github/workflows/build.yaml
  .github/workflows/build_app.yaml
  .github/workflows/publish_play_store_update.yaml
  .github/workflows/release_sdk.yaml
  CONTRIBUTING.md
  gradle/libs.versions.toml
  lib/lib.gradle.kts
  lib/src/main/java/com/smileidentity/SmileIDCrashReporting.kt
Labels: Review effort 2/5

#693 Fix Selfie Capture Instructions Overlap with FaceView 😶‍🌫️
  CHANGELOG.md
  lib/src/main/java/com/smileidentity/compose/selfie/SelfieCaptureScreen.kt
Labels: Review effort 2/5
