Repository smileidentity/android, pull requests merged in 2025-08, with the labels that each got.

#697 Improve emulator check
  lib/src/main/java/com/smileidentity/metadata/LocalMetadataProvider.kt
  lib/src/main/java/com/smileidentity/metadata/device/DeviceInformation.kt
  lib/src/main/java/com/smileidentity/metadata/models/MetadataKey.kt
  lib/src/main/java/com/smileidentity/metadata/models/Metadatum.kt
  lib/src/main/java/com/smileidentity/metadata/updaters/BuildInfoMetadata.kt
Labels: Review effort 3/5

#705 Removes unused unknown location info object
  lib/src/main/java/com/smileidentity/metadata/updaters/LocationMetadata.kt
Labels: Review effort 1/5

#703 Setup SmileID Instructions Screen 📜
  gradle/libs.versions.toml
  ui/src/androidTest/java/com/smileidentity/ui/ExampleInstrumentedTest.kt
  ui/src/androidTest/java/com/smileidentity/ui/SmileIDInstructionsScreenTest.kt
  ui/src/main/java/com/smileidentity/ui/SmileIDInstructionsScreen.kt
  ui/src/main/java/com/smileidentity/ui/components/SmileIDButton.kt
  ui/src/main/res/drawable/si_logo.xml
  ui/ui.gradle.kts
Labels: Review effort 2/5

#711 Introduce Builder Pattern Navigation 👷🏽 🏗️
  navigation/src/main/java/com/smileidentity/navigation/builder/BuilderNavigation.kt
  navigation/src/main/java/com/smileidentity/navigation/dsl/SmileIDDsl.kt
  navigation/src/main/java/com/smileidentity/navigation/graph/GraphNavigation.kt
  navigation/src/main/java/com/smileidentity/navigation/navigation/SmileIDNavigationHost.kt
Labels: Review effort 3/5

#712 Setting up Identity Scanner ViewModels 🫵
  navigation/src/main/java/com/smileidentity/navigation/navigation/SmileIDNavigationHost.kt
  navigation/src/main/java/com/smileidentity/navigation/ui/OrchestratedCaptureScreen.kt
  navigation/src/main/java/com/smileidentity/navigation/ui/OrchestratedInstructionsScreen.kt
  navigation/src/main/java/com/smileidentity/navigation/ui/OrchestratedPreviewScreen.kt
  navigation/src/main/java/com/smileidentity/navigation/ui/OrchestratedProcessingScreen.kt
  navigation/src/main/java/com/smileidentity/navigation/viewmodel/IdentityViewModel.kt
  ui/src/androidTest/java/com/smileidentity/ui/SmileIDCaptureScreenTest.kt
  ui/src/androidTest/java/com/smileidentity/ui/SmileIDInstructionsScreenTest.kt
  ui/src/androidTest/java/com/smileidentity/ui/SmileIDPreviewScreenTest.kt
  ui/src/androidTest/java/com/smileidentity/ui/SmileIDProcessingScreenTest.kt
  ui/src/main/java/com/smileidentity/ui/screens/SmileIDCaptureScreen.kt
  ui/src/main/java/com/smileidentity/ui/screens/SmileIDInstructionsScreen.kt
  ui/src/main/java/com/smileidentity/ui/screens/SmileIDPreviewScreen.kt
  ui/src/main/java/com/smileidentity/ui/screens/SmileIDProcessingScreen.kt
  ui/src/main/java/com/smileidentity/ui/viewmodel/DocumentScanViewModel.kt
  ui/src/main/java/com/smileidentity/ui/viewmodel/IdentityScanViewModel.kt
  ui/src/main/java/com/smileidentity/ui/viewmodel/SelfieScanViewModel.kt
  ui/ui.gradle.kts
Labels: Review effort 2/5

#698 Face Detection using Camera2Interop 📸
  camera/camera.gradle.kts
  camera/src/main/AndroidManifest.xml
  camera/src/main/java/com/smileidentity/camera/ui/CameraPreview.kt
  camera/src/main/java/com/smileidentity/camera/util/Util.kt
  camera/src/main/java/com/smileidentity/camera/viewmodel/CameraPreviewViewModel.kt
  gradle/libs.versions.toml
  sample/sample.gradle.kts
  ui/src/main/java/com/smileidentity/ui/components/SmileIDCameraPreview.kt
  ui/src/main/java/com/smileidentity/ui/screens/SmileIDCaptureScreen.kt
  ui/src/main/java/com/smileidentity/ui/utils/ViewModelUtil.kt
Labels: Review effort 4/5

#714 Setting up Networking Layer :neckbeard:
  gradle/libs.versions.toml
  networking/networking.gradle.kts
  networking/src/androidTest/java/com/smileidentity/networking/ExampleInstrumentedTest.kt
  networking/src/main/java/com/smileidentity/networking/api/SmileAPI.kt
  networking/src/main/java/com/smileidentity/networking/di/JsonModule.kt
  networking/src/main/java/com/smileidentity/networking/di/NetworkModule.kt
  networking/src/main/java/com/smileidentity/networking/interceptor/GzipRequestInterceptor.kt
  networking/src/main/java/com/smileidentity/networking/interceptor/SmileHeaderAuthInterceptor.kt
  networking/src/main/java/com/smileidentity/networking/models/Authentication.kt
  networking/src/test/java/com/smileidentity/networking/ExampleUnitTest.kt
  networking/src/test/java/com/smileidentity/networking/interceptor/GzipRequestInterceptorTest.kt
  networking/src/test/java/com/smileidentity/networking/interceptor/SmileHeaderAuthInterceptorTest.kt
Labels: Review effort 3/5

#724 Sample v12 App Setup 🍎
  sample/src/main/AndroidManifest.xml
  sample/src/main/java/com/smileidentity/sample/activity/V12Activity.kt
  sample/src/main/java/com/smileidentity/sample/compose/SettingsScreen.kt
  sample/src/main/res/values/strings.xml
Labels: Possible security concern, Review effort 2/5

#726 flatten build info into separate metadata keys
  lib/src/main/java/com/smileidentity/metadata/models/MetadataKey.kt
  lib/src/main/java/com/smileidentity/metadata/models/Metadatum.kt
  lib/src/main/java/com/smileidentity/metadata/updaters/BuildInfoMetadata.kt
Labels: Review effort 3/5

#727 Setup Theming and Typography 🌻
  navigation/src/main/java/com/smileidentity/navigation/ui/OrchestratedCaptureScreen.kt
  navigation/src/main/java/com/smileidentity/navigation/ui/OrchestratedInstructionsScreen.kt
  navigation/src/main/java/com/smileidentity/navigation/ui/OrchestratedPreviewScreen.kt
  navigation/src/main/java/com/smileidentity/navigation/ui/OrchestratedProcessingScreen.kt
  ui/src/main/java/com/smileidentity/ui/design/SmileIDTheme.kt
  ui/src/main/java/com/smileidentity/ui/design/colors/Colors.kt
  ui/src/main/java/com/smileidentity/ui/design/typography/Typography.kt
  ui/src/main/java/com/smileidentity/ui/previews/PreviewContent.kt
  ui/src/main/java/com/smileidentity/ui/screens/SmileIDInstructionsScreen.kt
  ui/src/main/res/values/font_certs.xml
Labels: Review effort 3/5

#728 Working on Instructions Screen 📨 📜
  navigation/src/main/java/com/smileidentity/navigation/ui/OrchestratedCaptureScreen.kt
  navigation/src/main/java/com/smileidentity/navigation/ui/OrchestratedInstructionsScreen.kt
  navigation/src/main/java/com/smileidentity/navigation/ui/OrchestratedPreviewScreen.kt
  navigation/src/main/java/com/smileidentity/navigation/ui/OrchestratedProcessingScreen.kt
  ui/src/main/java/com/smileidentity/ui/components/SmileIDButton.kt
  ui/src/main/java/com/smileidentity/ui/screens/SmileIDCaptureScreen.kt
  ui/src/main/java/com/smileidentity/ui/screens/SmileIDInstructionsScreen.kt
  ui/src/main/java/com/smileidentity/ui/screens/SmileIDPreviewScreen.kt
  ui/src/main/java/com/smileidentity/ui/screens/SmileIDProcessingScreen.kt
Labels: Review effort 2/5
